name: CI/CD Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Docker environment
        run: docker-compose up -d
      - name: npm ci and test
        run: |
          npm ci
          npm test
      - name: Stop Docker environment
        if: always()
        run: docker-compose down

  deploy_vercel:
    runs-on: ubuntu-latest
    needs: build_test_and_deploy
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to prod
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

  trigger-terraform-provide:
    runs-on: ubuntu-latest
    needs: deploy_vercel
    steps:
      - name: Déclencher Terraform Provide
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONNAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/SlaveofChrist/repo-terraform/dispatches \
            -d '{"event_type": "provide"}'