name: Vercel Production Deployment #test + merge automatique

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      branches-ignore:
        - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test_and_deploy:
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and test
        run: |
          npm ci
          npm test
  merge:
    needs: build_test_and_deploy
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}  # Ne pas merger si c'est déjà main

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge feature branch into main
        run: |
          git config --global user.email "elielwotobe@gmail.com"
          git config --global user.name "Eliel"
          git fetch origin ${{ github.ref_name }}
          git merge origin/${{ github.ref_name }} --no-ff --commit -m "Auto-merge ${{ github.ref_name }}"
          git push origin main